### ISSUE TITLE
Exporter: panic: `binder.rs`: "out of range when instantiating"

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#1046]
The exporter panics with messages like `type parameter `T/#1` (T/#1/1) out of range when instantiating, args=[typenum::UTerm]` or `
const parameter `'file/#2` ('file/#2/2) out of range when instantiating args=[read::any::File<'data/#0, R/#1>, 'data/#0]`.

That comes from `rustc_type_ir/src/binder.rs:697:9` (for type parameters) and `rustc_type_ir/src/binder.rs:769:9` (for const parameters).

<details><summary>Crate `generic-array@1.1.0`</summary>
  
  
```
thread 'rustc' panicked at /rustc/86d69c705a552236a622eee3fdea94bf13c5f102/compiler/rustc_type_ir/src/binder.rs:697:9:
type parameter `T/#1` (T/#1/1) out of range when instantiating, args=[typenum::UTerm]
```
</details>

<details><summary>Crate `object@0.36.5`</summary>
  
  
```
thread 'rustc' panicked at /rustc/86d69c705a552236a622eee3fdea94bf13c5f102/compiler/rustc_type_ir/src/binder.rs:769:9:
const parameter `'file/#2` ('file/#2/2) out of range when instantiating args=[read::any::File<'data/#0, R/#1>, 'data/#0]
```
</details>

<details><summary>Crate `anstream@0.6.17`</summary>
  
  
```
thread 'rustc' panicked at /rustc/86d69c705a552236a622eee3fdea94bf13c5f102/compiler/rustc_type_ir/src/binder.rs:769:9:
const parameter `'w/#1` ('w/#1/1) out of range when instantiating args=[&'_/#0 mut T/#1]
```
</details>

<details><summary>Crate `der@0.7.9`</summary>
  
  
```
thread 'rustc' panicked at /rustc/86d69c705a552236a622eee3fdea94bf13c5f102/compiler/rustc_type_ir/src/binder.rs:769:9:
const parameter `'a/#1` ('a/#1/1) out of range when instantiating args=[core::option::Option<T/#0>]
```
</details>

<details><summary>Crate `crc@3.2.1`</summary>
  
  
```
thread 'rustc' panicked at /rustc/86d69c705a552236a622eee3fdea94bf13c5f102/compiler/rustc_type_ir/src/binder.rs:697:9:
type parameter `W/#1` (W/#1/1) out of range when instantiating, args=[Table<L/#0>]
```
</details>

<details><summary>Crate `aws-smithy-types@1.2.8`</summary>
  
  
```
thread 'rustc' panicked at /rustc/86d69c705a552236a622eee3fdea94bf13c5f102/compiler/rustc_type_ir/src/binder.rs:769:9:
const parameter `'a/#1` ('a/#1/1) out of range when instantiating args=[config_bag::storable::StoreReplace<U/#0>]
```
</details>

<details><summary>Crate `nalgebra@0.33.1`</summary>
  
  
```
thread 'rustc' panicked at /rustc/86d69c705a552236a622eee3fdea94bf13c5f102/compiler/rustc_type_ir/src/binder.rs:697:9:
type parameter `T/#3` (T/#3/3) out of range when instantiating, args=[base::default_allocator::DefaultAllocator, base::dimension::Const<R/#0>, base::dimension::Const<C/#1>]
```
</details>

<details><summary>Crate `diesel@2.2.4`</summary>
  
  
```
thread 'rustc' panicked at /rustc/86d69c705a552236a622eee3fdea94bf13c5f102/compiler/rustc_type_ir/src/binder.rs:769:9:
const parameter `'conn/#3` ('conn/#3/3) out of range when instantiating args=[T/#0, Alias(Projection, AliasTy { args: [T/#0], def_id: DefId(0:315 ~ diesel[542a]::connection::Connection::Backend), .. }), B/#1]
```
</details>

<details><summary>Crate `sqlx-sqlite@0.8.2`</summary>
  
  
```
thread 'rustc' panicked at /rustc/86d69c705a552236a622eee3fdea94bf13c5f102/compiler/rustc_type_ir/src/binder.rs:769:9:
const parameter `'r/#1` ('r/#1/1) out of range when instantiating args=[database::Sqlite]
```
</details>

<details><summary>Crate `wayland-client@0.31.7`</summary>
  
  
```
thread 'rustc' panicked at /rustc/86d69c705a552236a622eee3fdea94bf13c5f102/compiler/rustc_type_ir/src/binder.rs:769:9:
const parameter `'a/#1` ('a/#1/1) out of range when instantiating args=[protocol::wl_display::WlDisplay]
```
</details>

<details><summary>Crate `sqlx-mysql@0.8.2`</summary>
  
  
```
thread 'rustc' panicked at /rustc/86d69c705a552236a622eee3fdea94bf13c5f102/compiler/rustc_type_ir/src/binder.rs:769:9:
const parameter `'r/#1` ('r/#1/1) out of range when instantiating args=[database::MySql]
```
</details>

<details><summary>Crate `sqlx-postgres@0.8.2`</summary>
  
  
```
thread 'rustc' panicked at /rustc/86d69c705a552236a622eee3fdea94bf13c5f102/compiler/rustc_type_ir/src/binder.rs:769:9:
const parameter `'r/#1` ('r/#1/1) out of range when instantiating args=[database::Postgres]
```
</details>

<details><summary>Crate `asynchronous-codec@0.7.0`</summary>
  
  
```
thread 'rustc' panicked at /rustc/86d69c705a552236a622eee3fdea94bf13c5f102/compiler/rustc_type_ir/src/binder.rs:769:9:
const parameter `'a/#1` ('a/#1/1) out of range when instantiating args=[codec::bytes::BytesCodec]
```
</details>

<details><summary>Crate `logos@0.14.2`</summary>
  
  
```
thread 'rustc' panicked at /rustc/86d69c705a552236a622eee3fdea94bf13c5f102/compiler/rustc_type_ir/src/binder.rs:769:9:
const parameter `'a/#1` ('a/#1/1) out of range when instantiating args=[str]
```
</details>

cc @Nadrieril, that might find this either (or both) amusing and depressing 😁

**Comment by Nadrieril** [comment]
Can you minimize any of that? And are you sure this isn't related to GATs?

**Comment by W95Psp** [comment]
Sure, will try to minimize as soon as possible. I have no idea, those errors are new, just saw that this morning, I spent no time investigating.
But that's very possible!

**Comment by W95Psp** [comment]
(looking at the names of the crates, that would not be so surprising to see GATs in there)

**Comment by W95Psp** [comment]
@Nadrieril, you're right, that's some bad owner id in HIR!

Repro:
```rust
trait Tr {
    type Ty<X>;
}

impl Tr for () {
    type Ty<X> = Option<X>;
}
```
[Open this code snippet in the playground](https://hax-playground.cryspen.com/#fstar/381bd0f7b0/gist=91dcaff034a9929a3333d685262eb98c)

Should be fairly easy to fix!

**Comment by W95Psp** [comment]
Maybe the easiest fix is to switch to `FullDef` :D 
I'm looking a bit at it @Nadrieril, I can't find the "impl expr" information for associated types in `FullDef`, e.g. `impl X for ... { type T = Something; }` where `trait X {type T: Super;}`, it's somewhere already?

**Comment by Nadrieril** [comment]
It's either in AssocItem or it's one of the last missing things.

**Comment by Nadrieril** [comment]
Oh actually, it's in the provided `FullDef`: `FullDefKind::Impl { items }` contains the `FullDef` of each item, wihch it itself `AssocTy`/`AssocConst`/`AssocFn` and have the right predicates.

**Comment by Nadrieril** [comment]
I added this info in https://github.com/hacspec/hax/pull/1069

**Comment by W95Psp** [comment]
Great, thank you! Will try to switch to FullDef asap :)

**Comment by maximebuyse** [comment]
This is fixed on main, though it is unclear what fixed it.

**Comment by Nadrieril** [comment]
Possibly the switch to FullDef :)

**Comment by maximebuyse** [comment]
> Possibly the switch to FullDef :)

The switch to FullDef is still experimental. I actually tried this to see if the switch to FullDef was fixing the issue, and discovered that it was working even without FullDef...

**Comment by Nadrieril** [comment]
Oh! Nice :)
