### ISSUE TITLE
Build error: binaries seems cached to eagerly

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#1145]
@franziskuskiefer reporting the following error after updating a local checkout of hax and running `./setup.sh`:

```
Caused by:
  process didn't exit successfully: `/Users/franziskus/cryspen/workbench/hax/target/release/build/hax-engine-names-extract-585571f63244d874/build-script-build` (exit status: 101)
  --- stderr
      Finished `dev` profile [unoptimized + debuginfo] target(s) in 2.51s
  thread 'main' panicked at /Users/franziskus/cryspen/workbench/hax/hax-types/src/driver_api.rs:52:72:
  called `Result::unwrap()` on an `Err` value: Message("unknown variant `Abi`, expected one of `Rust`, `C`, `Other`")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

  thread 'main' panicked at engine/names/extract/build.rs:113:19:
  error while parsing JSON: EOF while parsing a value at line 1 column 0

  String was:
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This seems to be a problem of caching: the build script of the crate `names` is parsing JSON using the schemas defined post https://github.com/hacspec/hax/pull/1122, which adds the type `Abi`, while the JSON received appears to have no such `Abi` enum.

**Comment by karthikbhargavan** [comment]
`cargo clean` appears to fix the issue, but this should be done within `setup.sh` or something.
