### ISSUE TITLE
binary hax-engine not found unless run `eval $(opam env)`

### ISSUE THREAD

**Issue by geonnave** [hacspec/hax#329]
I installed `hax` via the manual approach (`setup.sh`) on MacOS Ventura, M1.

I am running a command that looks like this: `cargo-hax -C -p edhoc-rs -p edhoc-consts --no-default-features --features="crypto-hacspec, ead-none" --release \; into -i '-c_wrapper::** -edhoc_rs::generate_connection_identifier_cbor -edhoc_rs::generate_connection_identifier' fstar`

With that I get the error `The binary [hax-engine] was not found in your [PATH]`.

<details><summary>Full output when FAIL</summary>
<p>

```
cargo-hax -C -p edhoc-rs -p edhoc-consts --no-default-features --features="crypto-hacspec, ead-none" --release \; into -i '-c_wrapper::** -edhoc_rs::generate_connection_identifier_cbor -edhoc_rs::generate_connection_identifier' fstar
   Compiling edhoc-consts v0.1.0 (/Users/geovane/Developer/inria/dev/edhoc-rs-FORK/consts)
warning: unused import: `super::structs::*`
   --> consts/src/lib.rs:225:9
    |
225 |     use super::structs::*;
    |         ^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_imports)]` on by default

thread 'rustc' panicked at 'attempted to read from stolen value: rustc_middle::thir::Thir', cli/driver/src/exporter.rs:142:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: The THIR body of item DefId(0:57 ~ edhoc_consts[76f7]::structs::BytesSuites::{constant#0}) was stolen.
       This is not supposed to happen.
       This is a bug in Hax's frontend.
       This is discussed in issue https://github.com/hacspec/hacspec-v2/issues/27.
       Please comment this issue if you see this error message!
  --> consts/src/lib.rs:69:33
   |
69 |     pub type BytesSuites = [u8; SUITES_LEN];
   |                                 ^^^^^^^^^^

thread 'rustc' panicked at 'attempted to read from stolen value: rustc_middle::thir::Thir', cli/driver/src/exporter.rs:142:22
error: The THIR body of item DefId(0:59 ~ edhoc_consts[76f7]::structs::BytesSupportedSuites::{constant#0}) was stolen.
       This is not supposed to happen.
       This is a bug in Hax's frontend.
       This is discussed in issue https://github.com/hacspec/hacspec-v2/issues/27.
       Please comment this issue if you see this error message!
  --> consts/src/lib.rs:70:42
   |
70 |     pub type BytesSupportedSuites = [u8; SUPPORTED_SUITES_LEN];
   |                                          ^^^^^^^^^^^^^^^^^^^^

? The binary [hax-engine] was not found in your [PATH]. Should I try to download it from GitHub? (Y/n)
                                                                                                            Building [=======================>   ] 77/84: edhoc-consts
thread 'rustc' panicked at 'The binary [hax-engine] was not found in your [PATH].', cli/driver/src/exporter.rs:258:10
warning: `edhoc-consts` (lib) generated 1 warning
error: could not compile `edhoc-consts` (lib) due to 2 previous errors; 1 warning emitted
```

</p>
</details> 

After some tweaking around, I found that I need to run `eval $(opam env)` in the shell to make `hax-engine` available. After that `cargo-hax` works.

<details><summary>Full output when OK</summary>
<p>

```
cargo-hax -C -p edhoc-rs -p edhoc-consts --no-default-features --features="crypto-hacspec, ead-none" --release \; into -i '-c_wrapper::** -edhoc_rs::generate_connection_identifier_cbor -edhoc_rs::generate_connection_identifier' fstar
   Compiling edhoc-consts v0.1.0 (/Users/geovane/Developer/inria/dev/edhoc-rs-FORK/consts)
warning: unused import: `super::structs::*`
   --> consts/src/lib.rs:225:9
    |
225 |     use super::structs::*;
    |         ^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_imports)]` on by default

thread 'rustc' panicked at 'attempted to read from stolen value: rustc_middle::thir::Thir', cli/driver/src/exporter.rs:142:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: The THIR body of item DefId(0:57 ~ edhoc_consts[76f7]::structs::BytesSuites::{constant#0}) was stolen.
       This is not supposed to happen.
       This is a bug in Hax's frontend.
       This is discussed in issue https://github.com/hacspec/hacspec-v2/issues/27.
       Please comment this issue if you see this error message!
  --> consts/src/lib.rs:69:33
   |
69 |     pub type BytesSuites = [u8; SUITES_LEN];
   |                                 ^^^^^^^^^^

thread 'rustc' panicked at 'attempted to read from stolen value: rustc_middle::thir::Thir', cli/driver/src/exporter.rs:142:22
error: The THIR body of item DefId(0:59 ~ edhoc_consts[76f7]::structs::BytesSupportedSuites::{constant#0}) was stolen.
       This is not supposed to happen.
       This is a bug in Hax's frontend.
       This is discussed in issue https://github.com/hacspec/hacspec-v2/issues/27.
       Please comment this issue if you see this error message!
  --> consts/src/lib.rs:70:42
   |
70 |     pub type BytesSupportedSuites = [u8; SUPPORTED_SUITES_LEN];
   |                                          ^^^^^^^^^^^^^^^^^^^^

note: Writing file "/Users/geovane/Developer/inria/dev/edhoc-rs-FORK/consts/proofs/fstar/extraction/Edhoc_consts.fst"

note: Writing file "/Users/geovane/Developer/inria/dev/edhoc-rs-FORK/consts/proofs/fstar/extraction/Edhoc_consts.Cbor.fst"

note: Writing file "/Users/geovane/Developer/inria/dev/edhoc-rs-FORK/consts/proofs/fstar/extraction/Edhoc_consts.Common_edhoc_parsing.fst"

note: Writing file "/Users/geovane/Developer/inria/dev/edhoc-rs-FORK/consts/proofs/fstar/extraction/Edhoc_consts.Consts.fst"

note: Writing file "/Users/geovane/Developer/inria/dev/edhoc-rs-FORK/consts/proofs/fstar/extraction/Edhoc_consts.Helpers.fst"

note: Writing file "/Users/geovane/Developer/inria/dev/edhoc-rs-FORK/consts/proofs/fstar/extraction/Edhoc_consts.Structs.fst"

warning: `edhoc-consts` (lib) generated 1 warning
error: could not compile `edhoc-consts` (lib) due to 2 previous errors; 1 warning emitted
```

</p>
</details> 

(note that some errors are specific to my application)

**Comment by W95Psp** [comment]
Hi Geonave!
Thanks for the report! (also, sorry, I had no time to test the things you sent me on Zulip :/)

The normal setup of `opam` usually implies writing `eval $(opam env)` to your `bashrc`/`init.zsh`/whatever your shell is. Without that, the directory in which opam installs binaries is not in PATH.

But anyway, that's indeed an issue. I am going to add some diagnostic information in the error message when the engine is not found.
