### ISSUE TITLE
Regression in trait resolution

### ISSUE THREAD

**Issue by maximebuyse** [hacspec/hax#974]
I have the following frontend error:
```
thread 'rustc' panicked at compiler/rustc_trait_selection/src/traits/normalize.rs:151:9:
Normalizing support::data_source::DataSource<'^1_0.Named(DefId(0:1727 ~ sandwich[df1c]::tunnel::tls::support::configuration_read_certificate::'_), "'_")> without wrapping in a `Binder`
```

The bug is a regression from https://github.com/hacspec/hax/pull/906 (extraction works with the commit before merging this). I tried to minimize but couldn't.
Here is the trace:
```
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─  0ms TRACE Enters sinto (rustc_middle::ty::PolyTraitRef<'tcx>)
│ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ │ ├─┐impl_expr owner_id=DefId(0:274 ~ sandwich[df1c]::implementation::openssl3_impl::tunnel::context::{impl#4}::fill_certificate_trust_store), tref=Binder { value: <(pb_api::ASN1EncodingFormat, support::data_source::DataSource<'aaa>) as std::marker::Sized>, bound_vars: [] }
thread 'rustc' panicked at compiler/rustc_trait_selection/src/traits/normalize.rs:151:9:
Normalizing support::data_source::DataSource<'^1_0.Named(DefId(0:810 ~ sandwich[df1c]::tunnel::tls::support::configuration_read_certificate::'aaa), "'aaa")> without wrapping in a `Binder`
```

**Comment by Nadrieril** [comment]
Do you have a minimal reproducer?

**Comment by W95Psp** [comment]
Reproducer:
```rust
use std::borrow::Cow;

enum DataSource<'data> {
    Fs(Vec<u8>),
    Bytes(Cow<'data, [u8]>),
    String(Cow<'data, str>),
}

type Error = u8;


struct Cert;

fn configuration_read_certificate(
    cert: &Cert,
) -> Result<(bool, DataSource<'_>), Error> {
    todo!()
}

impl AsRef<Option<&Cert>> for Cert {
    fn as_ref(&self) -> &Option<&Cert> {
        // Some(self)
        todo!()
    }
}

struct X509Identity {
    certificate: Cert
}

trait Ossl {}

fn ssl_context_set_identity<OsslInterface>(
    identity: &X509Identity,
) -> Result<(), Error>
where
    OsslInterface: Ossl,
{
    let (format, data_source) = identity
        .certificate
        .as_ref()
        .ok_or(3)
        .and_then(configuration_read_certificate)
        .map_err(|e| e >> 3)?;
    Ok(())
}

```
[Open this code snippet in the playground](https://hax-playground.cryspen.com/#fstar/496e381186/gist=2a9ba90e5197bb0d7a4525b56589da21)


will minimize

**Comment by Nadrieril** [comment]
I believe this is fixed by https://github.com/hacspec/hax/pull/977

**Comment by franziskuskiefer** [comment]
@maximebuyse please close this when you can confirm that it is fixed.
